# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 06:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170308_0919'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='sub_title',
            field=models.CharField(max_length=256, null=True, verbose_name='子标题'),
        ),
    ]
