# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_article_sub_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.CharField(default='Denzel', max_length=256, verbose_name='作者'),
        ),
    ]
