# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20170309_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tag',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
